liip_imagine:
    twig:
        mode: lazy

    resolvers:
        default:
            web_path:
                web_root: "%kernel.project_dir%/public"
                cache_prefix: "media/cache"

    filter_sets:
        # default cache behavior
        cache: ~

        # Poster size (414x616)
        poster:
            quality: 85
            filters:
                thumbnail: { size: [414, 616], mode: outbound }

        # Thumbnail size (60x60)
        thumb:
            quality: 70
            filters:
                thumbnail: { size: [60, 60], mode: outbound }

        # Profile size (150x150)
        profile:
            quality: 80
            filters:
                thumbnail: { size: [ 150, 150 ], mode: outbound }

        poster_webp:
            format: webp
            quality: 80
            filters:
                thumbnail: { size: [ 414, 616 ], mode: outbound }

        thumb_webp:
            format: webp
            quality: 60
            filters:
                thumbnail: { size: [60, 60], mode: outbound }

        profile_webp:
            format: webp
            quality: 60
            filters:
                thumbnail: { size: [ 150, 150 ], mode: outbound }
