parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true
        bind:
            $projectDir: '%kernel.project_dir%'

    App\:
        resource: '../src/'

    # Event listeners
    App\EventListener\SecurityHeadersListener:
        tags:
            - { name: kernel.event_listener, event: kernel.response, method: onKernelResponse }
